import { defineConfig } from 'vitepress'
import { withPwa } from '@vite-pwa/vitepress'
import { tabsMarkdownPlugin } from 'vitepress-plugin-tabs'

export default withPwa(
  defineConfig({
    lang: 'ja-JP',
    title: 'Web フロントエンド入門',
    description: 'Web フロントエンドをこれから学ぶ人向けの学習コンテンツ',
    lastUpdated: true,
    markdown: {
      // 本コースで実際に使う言語だけ Shiki にロードさせる。
      // 既定では C++ / WebAssembly などの未使用言語までチャンクが
      // 生成されてバンドルが膨らむため、明示で抑える。
      languages: [
        'ts', 'tsx', 'js', 'jsx',
        'html', 'css', 'json', 'jsonc',
        'bash', 'sh', 'yaml',
        'md', 'markdown',
        'graphql', 'http',
      ],
      config(md) {
        md.use(tabsMarkdownPlugin)
      },
    },
    vue: {
      template: {
        compilerOptions: {
          isCustomElement: (tag) => tag === 'selectedcontent',
        },
      },
    },
    // PWA 設定。@vite-pwa/vitepress でデスクトップ / モバイルに
    // インストール可能にする（manifest + Service Worker + アイコン）。
    // アイコンは `pwa-assets.config.ts` で docs/public/logo.svg から生成。
    pwa: {
      registerType: 'autoUpdate',
      manifest: {
        name: 'Web フロントエンド入門',
        short_name: 'Web 入門',
        description: 'Web フロントエンドをこれから学ぶ人向けの学習コンテンツ',
        theme_color: '#1e40af',
        background_color: '#faf5e9',
        lang: 'ja',
        display: 'standalone',
        start_url: '/',
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // VitePress のビルド成果物は総量が大きいのでファイルサイズ上限を上げる。
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
        globPatterns: ['**/*.{js,css,html,woff2,png,svg,ico,webp,json}'],
      },
    },
    head: [
      ['link', { rel: 'icon', href: '/favicon.ico', sizes: '48x48' }],
      ['link', { rel: 'icon', href: '/logo.svg', type: 'image/svg+xml' }],
      ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon-180x180.png' }],
      // theme-color はモバイルブラウザの URL バー / タスクスイッチャー背景に反映される。
      // custom.css の --vp-c-bg と一致させ、ライト = クリーム、ダーク = ウォームチャコール。
      ['meta', { name: 'theme-color', media: '(prefers-color-scheme: light)', content: '#faf5e9' }],
      ['meta', { name: 'theme-color', media: '(prefers-color-scheme: dark)', content: '#26201a' }],
    ],
    themeConfig: {
      nav: [{ text: 'ホーム', link: '/' }],
      sidebar: [
        { text: 'トップ', link: '/' },
        { text: 'はじめに', link: '/introduction/' },
        {
          text: '1. HTML / CSS',
          collapsed: true,
          items: [
            { text: 'lesson01: HTML ってなに？', link: '/lessons/lesson01/' },
            { text: 'lesson02: テキストを書く', link: '/lessons/lesson02/' },
            { text: 'lesson03: リストで並べる', link: '/lessons/lesson03/' },
            { text: 'lesson04: リンクと画像', link: '/lessons/lesson04/' },
            { text: 'lesson05: ページの骨格を組む', link: '/lessons/lesson05/' },
            { text: 'lesson06: フォームを作る', link: '/lessons/lesson06/' },
            { text: 'lesson07: CSS を当てる', link: '/lessons/lesson07/' },
            { text: 'lesson08: クラスと状態', link: '/lessons/lesson08/' },
            { text: 'lesson09: セレクタの組み合わせと詳細度', link: '/lessons/lesson09/' },
            { text: 'lesson10: 色と文字を整える', link: '/lessons/lesson10/' },
            { text: 'lesson11: ボックスモデルで余白を作る', link: '/lessons/lesson11/' },
            { text: 'lesson12: Flexbox とレスポンシブ', link: '/lessons/lesson12/' },
            { text: 'lesson13: CSS Grid で 2 次元レイアウト', link: '/lessons/lesson13/' },
            { text: 'lesson14: Position と z-index', link: '/lessons/lesson14/' },
            { text: 'lesson15: Transition と hover アニメーション', link: '/lessons/lesson15/' },
            { text: 'lesson16: モダン CSS（:has / @layer / @scope / Container Queries / View Transitions）', link: '/lessons/lesson16/' },
            { text: 'lesson17: ネイティブ UI（details / dialog / popover）', link: '/lessons/lesson17/' },
          ],
        },
        {
          text: '2. JavaScript',
          collapsed: true,
          items: [
            { text: 'lesson18: 最初の JavaScript', link: '/lessons/lesson18/' },
            { text: 'lesson19: 値の種類', link: '/lessons/lesson19/' },
            { text: 'lesson20: 条件で分岐する', link: '/lessons/lesson20/' },
            { text: 'lesson21: 配列を扱う', link: '/lessons/lesson21/' },
            { text: 'lesson22: 繰り返し処理', link: '/lessons/lesson22/' },
            { text: 'lesson23: 関数', link: '/lessons/lesson23/' },
            { text: 'lesson24: スコープとクロージャ', link: '/lessons/lesson24/' },
            { text: 'lesson25: オブジェクト', link: '/lessons/lesson25/' },
            { text: 'lesson26: 分割代入とスプレッド', link: '/lessons/lesson26/' },
            { text: 'lesson27: 配列の変換', link: '/lessons/lesson27/' },
            { text: 'lesson28: Date で日付と時刻を扱う', link: '/lessons/lesson28/' },
            { text: 'lesson29: Web Storage で値をブラウザに保存する', link: '/lessons/lesson29/' },
            { text: 'lesson30: import / export でモジュール化', link: '/lessons/lesson30/' },
            { text: 'lesson31: 非同期処理の基本', link: '/lessons/lesson31/' },
            { text: 'lesson32: try / catch でエラー処理', link: '/lessons/lesson32/' },
            { text: 'lesson33: fetch で API から取得する', link: '/lessons/lesson33/' },
            { text: 'lesson34: JSON を読み書きする', link: '/lessons/lesson34/' },
            { text: 'lesson35: DOM を操作する', link: '/lessons/lesson35/' },
            { text: 'lesson36: イベントで画面を動かす', link: '/lessons/lesson36/' },
            { text: 'lesson37: URL と History API でページ遷移なしに URL を操作する', link: '/lessons/lesson37/' },
            { text: 'lesson38: デバッグに効く Console API', link: '/lessons/lesson38/' },
            { text: 'lesson39: 監視系 API（Intersection Observer / ResizeObserver / MutationObserver）', link: '/lessons/lesson39/' },
            { text: 'lesson40: Intl API で国際化の基礎', link: '/lessons/lesson40/' },
          ],
        },
        {
          text: '3. TypeScript',
          collapsed: true,
          items: [
            { text: 'lesson41: TypeScript ってなに？', link: '/lessons/lesson41/' },
            { text: 'lesson42: 関数の型', link: '/lessons/lesson42/' },
            { text: 'lesson43: オブジェクトの型と type エイリアス', link: '/lessons/lesson43/' },
            { text: 'lesson44: interface と type の使い分け', link: '/lessons/lesson44/' },
            { text: 'lesson45: 配列・ユニオン・リテラル型・オプショナル', link: '/lessons/lesson45/' },
            { text: 'lesson46: unknown と never', link: '/lessons/lesson46/' },
            { text: 'lesson47: 型ガード', link: '/lessons/lesson47/' },
            { text: 'lesson48: 判別共用体', link: '/lessons/lesson48/' },
            { text: 'lesson49: ジェネリクス入門', link: '/lessons/lesson49/' },
            { text: 'lesson50: Utility Types で仕上げる', link: '/lessons/lesson50/' },
            { text: 'lesson51: tsconfig.json を読む', link: '/lessons/lesson51/' },
          ],
        },
        {
          text: '4. React',
          collapsed: true,
          items: [
            { text: 'lesson52: React ってなに？', link: '/lessons/lesson52/' },
            { text: 'lesson53: JSX を書く', link: '/lessons/lesson53/' },
            { text: 'lesson54: コンポーネントと props', link: '/lessons/lesson54/' },
            { text: 'lesson55: 配列を描画する', link: '/lessons/lesson55/' },
            { text: 'lesson56: state で状態を持つ', link: '/lessons/lesson56/' },
            { text: 'lesson57: イベントと配列のイミュータブル更新', link: '/lessons/lesson57/' },
            { text: 'lesson58: useReducer で複雑な state', link: '/lessons/lesson58/' },
            { text: 'lesson59: フォームと制御コンポーネント', link: '/lessons/lesson59/' },
            { text: 'lesson60: 条件で出し分ける', link: '/lessons/lesson60/' },
            { text: 'lesson61: 親子コンポーネントの連携', link: '/lessons/lesson61/' },
            { text: 'lesson62: Context API で多層バケツリレー回避', link: '/lessons/lesson62/' },
            { text: 'lesson63: useRef', link: '/lessons/lesson63/' },
            { text: 'lesson64: useEffect の基本', link: '/lessons/lesson64/' },
            { text: 'lesson65: useMemo で計算のメモ化', link: '/lessons/lesson65/' },
            { text: 'lesson66: カスタムフック', link: '/lessons/lesson66/' },
            { text: 'lesson67: React DevTools', link: '/lessons/lesson67/' },
            { text: 'lesson68: Error Boundary と Suspense', link: '/lessons/lesson68/' },
          ],
        },
        {
          text: '5. Next.js',
          collapsed: true,
          items: [
            { text: 'lesson69: Next.js ってなに？', link: '/lessons/lesson69/' },
            { text: 'lesson70: ページを増やしてリンクで移動する', link: '/lessons/lesson70/' },
            { text: 'lesson71: 共通レイアウトを作る', link: '/lessons/lesson71/' },
            { text: 'lesson72: Route Groups で整理する', link: '/lessons/lesson72/' },
            { text: 'lesson73: Server Component と Client Component', link: '/lessons/lesson73/' },
            { text: 'lesson74: Server Component でデータを取得する', link: '/lessons/lesson74/' },
            { text: 'lesson75: Next.js のキャッシュと revalidate', link: '/lessons/lesson75/' },
            { text: 'lesson76: next/image で画像最適化', link: '/lessons/lesson76/' },
            { text: 'lesson77: next/font でフォント', link: '/lessons/lesson77/' },
            { text: 'lesson78: 動的ルート', link: '/lessons/lesson78/' },
            { text: 'lesson79: エラーと見つからないページ', link: '/lessons/lesson79/' },
            { text: 'lesson80: Server Actions の最小形', link: '/lessons/lesson80/' },
            { text: 'lesson81: 送信状態とエラー表示', link: '/lessons/lesson81/' },
            { text: 'lesson82: Route Handlers の基本', link: '/lessons/lesson82/' },
            { text: 'lesson201: Route Handlers の入力検証と受信検証', link: '/lessons/lesson201/' },
            { text: 'lesson83: Proxy で認証前処理', link: '/lessons/lesson83/' },
            { text: 'lesson84: 環境変数の基本', link: '/lessons/lesson84/' },
            { text: 'lesson85: Tailwind CSS の紹介', link: '/lessons/lesson85/' },
            { text: 'lesson86: Metadata API で SEO を整える', link: '/lessons/lesson86/' },
            { text: 'lesson87: Loading UI と Streaming', link: '/lessons/lesson87/' },
            { text: 'lesson88: Vercel にデプロイする', link: '/lessons/lesson88/' },
          ],
        },
        {
          text: '6. ブラウザの仕組み',
          collapsed: true,
          items: [
            { text: 'lesson89: ブラウザと HTTP の基本', link: '/lessons/lesson89/' },
            { text: 'lesson90: DevTools の読み方', link: '/lessons/lesson90/' },
            { text: 'lesson91: HTTP キャッシュ', link: '/lessons/lesson91/' },
            { text: 'lesson92: 同時接続数と HTTP/2 / HTTP/3', link: '/lessons/lesson92/' },
            { text: 'lesson93: Cookie と Web セキュリティ', link: '/lessons/lesson93/' },
          ],
        },
        {
          text: '7. 実務で使う周辺知識',
          collapsed: true,
          items: [
            { text: 'lesson94: セマンティック HTML とアクセシビリティの基礎', link: '/lessons/lesson94/' },
            { text: 'lesson95: ARIA 属性とキーボード操作', link: '/lessons/lesson95/' },
            { text: 'lesson96: アクセシビリティの自動チェック（axe / Lighthouse / スクリーンリーダー）', link: '/lessons/lesson96/' },
            { text: 'lesson97: テスト入門 — Vitest でユニットテスト', link: '/lessons/lesson97/' },
            { text: 'lesson98: コンポーネントテスト — React Testing Library', link: '/lessons/lesson98/' },
            { text: 'lesson99: API モック — MSW（Mock Service Worker）', link: '/lessons/lesson99/' },
            { text: 'lesson100: E2E テスト — Playwright', link: '/lessons/lesson100/' },
            { text: 'lesson101: Core Web Vitals の 3 つの指標と Lighthouse', link: '/lessons/lesson101/' },
            { text: 'lesson102: バンドルサイズの最適化とコード分割', link: '/lessons/lesson102/' },
            { text: 'lesson103: 画像とフォントの最適化', link: '/lessons/lesson103/' },
            { text: 'lesson104: package.json と npm スクリプト', link: '/lessons/lesson104/' },
            { text: 'lesson105: Vite の仕組みを軽く', link: '/lessons/lesson105/' },
            { text: 'lesson106: ESLint / Prettier / Biome', link: '/lessons/lesson106/' },
            { text: 'lesson107: 次世代ツールチェイン（Biome / Oxc / Turbopack）', link: '/lessons/lesson107/' },
            { text: 'lesson108: Git の基本操作', link: '/lessons/lesson108/' },
            { text: 'lesson109: GitHub の PR とコードレビュー', link: '/lessons/lesson109/' },
            { text: 'lesson110: GitHub Actions で CI', link: '/lessons/lesson110/' },
            { text: 'lesson111: CI/CD パイプラインの設計', link: '/lessons/lesson111/' },
            { text: 'lesson112: React Hook Form の基本', link: '/lessons/lesson112/' },
            { text: 'lesson113: Zod でスキーマバリデーション', link: '/lessons/lesson113/' },
            { text: 'lesson114: 状態管理の地図（TanStack Query / Zustand / Jotai）', link: '/lessons/lesson114/' },
            { text: 'lesson115: Web Components 入門', link: '/lessons/lesson115/' },
            { text: 'lesson116: 環境変数とシークレット管理', link: '/lessons/lesson116/' },
            { text: 'lesson117: フィーチャーフラグ', link: '/lessons/lesson117/' },
            { text: 'lesson118: Content-Security-Policy（CSP）実践', link: '/lessons/lesson118/' },
            { text: 'lesson119: CORS の詳細', link: '/lessons/lesson119/' },
            { text: 'lesson120: 依存性セキュリティ（npm audit / Dependabot）', link: '/lessons/lesson120/' },
            { text: 'lesson121: OAuth / OIDC / JWT の概念', link: '/lessons/lesson121/' },
            { text: 'lesson122: WebSocket と Server-Sent Events（SSE）', link: '/lessons/lesson122/' },
            { text: 'lesson123: GraphQL と tRPC の地図', link: '/lessons/lesson123/' },
            { text: 'lesson124: Service Worker と PWA 深掘り', link: '/lessons/lesson124/' },
            { text: 'lesson125: IndexedDB 入門', link: '/lessons/lesson125/' },
            { text: 'lesson126: React Compiler', link: '/lessons/lesson126/' },
            { text: 'lesson127: Server Components の設計論', link: '/lessons/lesson127/' },
            { text: 'lesson128: エラートラッキング（Sentry）', link: '/lessons/lesson128/' },
            { text: 'lesson129: Web Analytics（Vercel Analytics / GA4）', link: '/lessons/lesson129/' },
            { text: 'lesson130: OGP と SEO 実践', link: '/lessons/lesson130/' },
            { text: 'lesson131: AI を前提にした開発（Copilot / Cursor / Claude Code）', link: '/lessons/lesson131/' },
          ],
        },
      ],
      outline: {
        label: '目次',
      },
      docFooter: {
        prev: '前のレッスン',
        next: '次のレッスン',
      },
      lastUpdated: {
        text: '最終更新',
        formatOptions: {
          dateStyle: 'medium',
          timeStyle: 'short',
        },
      },
      search: {
        provider: 'local',
        options: {
          translations: {
            button: { buttonText: '検索' },
            modal: {
              noResultsText: '見つかりませんでした',
              resetButtonTitle: 'リセット',
            },
          },
        },
      },
    },
  })
)
